### ISSUE TITLE
Error: A problem occurred configuring project ":app"

### ISSUE THREAD

**Issue by yinazh** [skcodestack/StoneVoicer-Demo#1]
Error:A problem occurred configuring project ':app'.
> executing external native build for cmake /home/peapad/Backup/user/workplace/StoneVoicer-Demo/app/CMakeLists.txt
I download this demo and build it with android studio, but it show this error, please help

**Comment by skcodestack** [comment]
Please ensure installed LLDB,CMake,NDK
